export const COMPANY_LIST = "COMPANY_LIST";
export const COMPANY_FAIL = "COMPANY_FAIL";
export const COMPANY_CREATE = "COMPANY_CREATE";
export const COMPANY_UPDATE ="COMPANY_UPDATE";
export const COMPANY_DELETE ="COMPANY_DELETE;";
export const IS_FETCH_COMPANY = "IS_FETCH_COMPANY";
