export const HOLIDAY_CREATE = "HOLIDAY_CREATE";
export const HOLIDAY_LIST = "HOLIDAY_LIST";
export const HOLIDAY_UPDATE = "HOLIDAY_UPDATE";
export const HOLIDAY_DELETE = "HOLIDAY_DELETE";
export const HOLIDAY_FAIL = "HOLIDAY_FAIL";
export const IS_FETCH_HOLIDAY = "IS_FETCH_HOLIDAY";
