export const PROJECT_CREATE = "PROJECT_CREATE";
export const PROJECT_FAIL = "PROJECT_FAIL";
export const PROJECT_LIST = "PROJECT_LIST";
export const PROJECT_UPDATE = "PROJECT_UPDATE";
export const PROJECT_DELETE = "PROJECT_DELETE";
export const IS_FETCH_PROJECT = "IS_FETCH_PROJECT";
