export const TIMESHEET_LIST = "TIMESHEET_LIST";
export const TIMESHEET_TEAM = "TIMESHEET_TEAM";
export const TIMESHEET_CREATE = "TIMESHEET_CREATE";
export const TIMESHEET_EDIT = "TIMESHEET_EDIT";
export const TIMESHEET_DELETE = "TIMESHEET_DELETE";
export const TIMESHEET_IMPORT = "TIMESHEET_IMPORT";
export const TIMESHEET_ERROR = "TIMESHEET_ERROR";