export const TIMELOG_LIST = "TIMELOG_LIST";
export const ALL_TIMELOG_LIST = "ALL_TIMELOG_LIST";
export const TIMELOG_CREATE = "TIMELOG_CREATE";
export const TIMELOG_UPDATE = "TIMELOG_UPDATE";
export const TIMELOG_DELETE = "TIMELOG_DELETE";
export const TIMELOG_FAIL = "TIMELOG_FAIL";
export const IS_FETCH_TIMELOG = "IS_FETCH_TIMELOG";
