export const TRAINING_LIST = "TRAINING_LIST";
export const TRAINING_LIST_FAIL = "TRAINING_LIST_FAIL";
export const IS_FETCH_TRAINING_LIST = "IS_FETCH_TRAINING_LIST";
export const CREATE_TRAINEE = "CREATE_TRAINEE";
export const UPDATE_TRAINEE = "UPDATE_TRAINEE";
export const DELETE_TRAINEE = "DELETE_TRAINEE";
